### PR TITLE
Percentage Prediction of a student

### PR DESCRIPTION
**Pull request by adityarajsahoo**
ML work to predict the percentage of a student based on the number of study hours. Also, obtain a heat map and
other plots for a better understanding of the result.
issue number #190

### CODE REVIEW

**Comment by Ayush7614** [comment]
mention your issue no

**Comment by adityarajsahoo** [comment]
issue no. 190

**Comment by adityarajsahoo** [comment]
@Ayush7614 I mentioned my issue number above

**Comment by Ayush7614** [comment]
Mention your issue no properly with #

**Comment by adityarajsahoo** [comment]
Oh ok just now mentioned in the top comment @Ayush7614

**Review by Ayush7614 — APPROVED** [review]

**Pull request merged**
