### PR TITLE
Shipping Cost Prediction

### PR DESCRIPTION
**Pull request by Praveenk8051**
Includes README.md(Description, evaluation metric used and Glimpse of visualization), ipynb format readable code and explanations.

### CODE REVIEW

**Comment by Ayush7614** [comment]
@Praveenk8051 mention yopur issue no

**Review by Ayush7614 — CHANGES_REQUESTED** [review]
Please add your issue no with # in comment section

**Comment by Praveenk8051** [comment]
#123

**Comment by Praveenk8051** [comment]
@Ayush7614 Is there anything pending from my side ?

**Pull request closed without merging**
